name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"
tasks = [ ]

[[processes]]
id = "process2"
name = "In Progress"
tasks = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "amk26wi7xd80lj7dmu126ny1"
  title = "Find Real-World Data"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "Normal"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "wryhdsk2vfg0dobff505s9zp"
  title = "Create ERD Diagram for Core Tables"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "High"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "sdfw1k78zn29eacbe288o809"
  title = "Create Functions & Procedures"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  priority = "High"
  linkCommits = [ ]

    [[processes.tasks.checkList]]
    id = "lfjwukbcmqdsqcv6wa0bttfc"
    title = "Function to Calculate Total Trade Value for a Specific Country"
    completed = false

    [[processes.tasks.checkList]]
    id = "x4v5xwtv8qt4p2t7bqd7hawa"
    title = "Function to Apply Tariff to a Commodity from a Specific Country"
    completed = false

  [[processes.tasks]]
  id = "jeg1djyctiw26d61sf8rkiye"
  title = "Make Documentation"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "Low"
  linkCommits = [ ]
